<a href="https://colab.research.google.com/github/crystalclcm/JobPostings/blob/main/Post_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd

In [2]:
APP_ID = "90fb93ab"
APP_KEY = "ac0d74800544bfc63431a2d3747a92c5"

In [ ]:
import requests
import pandas as pd
import time
import random

# 🔐 Insert your keys here (keep private!)
APP_ID = "90fb93ab"
APP_KEY = "ac0d74800544bfc63431a2d3747a92c5"

BASE_URL = "https://api.adzuna.com/v1/api/jobs/{country}/search/{page}"

roles = [
    "Accountant",
    "Financial Analyst",
    "Business Analyst",
    "Risk Analyst",
    "Software Engineer",
    "Data Analyst",
    "Data Engineer",
    "Cybersecurity Analyst"
]

countries = ["gb", "de", "nl", "us", "ca", "au"]  # UK, Germany, Netherlands, US, Canada, Australia

def fetch_adzuna_jobs(country, role, pages=10, results_per_page=50):
    all_results = []

    for page in range(1, pages + 1):
        print(f"Country: {country.upper()} | Role: {role} | Page: {page}")

        params = {
            "app_id": APP_ID,
            "app_key": APP_KEY,
            "results_per_page": results_per_page,
            "what": role,
            "content-type": "application/json"
        }

        url = BASE_URL.format(country=country, page=page)

        try:
            r = requests.get(url, params=params, timeout=15)
            if r.status_code != 200:
                print(f"  ⚠️ Status code {r.status_code} for {country} - {role} - page {page}")
                continue

            data = r.json()
            jobs = data.get("results", [])

            for job in jobs:
                all_results.append({
                    "role": role,
                    "country": country.upper(),
                    "job_title": job.get("title"),
                    "company": job.get("company", {}).get("display_name"),
                    "location": job.get("location", {}).get("display_name"),
                    "created": job.get("created"),
                    "redirect_url": job.get("redirect_url"),
                    "description": job.get("description")
                })

        except Exception as e:
            print(f"  ❌ Error for {country} - {role} - page {page}: {e}")

        time.sleep(random.uniform(1.0, 2.5))  # polite delay

    return all_results

all_results = []

for country in countries:
    for role in roles:
        results = fetch_adzuna_jobs(country, role, pages=10, results_per_page=50)
        all_results.extend(results)

df = pd.DataFrame(all_results)
print("Total rows scraped:", len(df))

df.to_csv("adzuna_expanded_combined.csv", index=False)
df.head()

Country: GB | Role: Accountant | Page: 1
Country: GB | Role: Accountant | Page: 2
Country: GB | Role: Accountant | Page: 3
Country: GB | Role: Accountant | Page: 4

In [3]:
import os
os.makedirs("data/post_ai/adzuna", exist_ok=True)

In [4]:
import requests
import pandas as pd

APP_ID = "90fb93ab"
APP_KEY = "ac0d74800544bfc63431a2d3747a92c5"

def get_adzuna_jobs(country_code, role):
    url = f"https://api.adzuna.com/v1/api/jobs/{country_code}/search/1"
    params = {
        "app_id": APP_ID,
        "app_key": APP_KEY,
        "results_per_page": 50,
        "what": role
    }

    response = requests.get(url, params=params).json()
    results = response.get("results", [])

    rows = []
    for job in results:
        rows.append({
            "job_title": job.get("title"),
            "job_description": job.get("description"),
            "country": country_code,
            "date_posted": job.get("created"),
            "source": "adzuna"
        })

    return pd.DataFrame(rows)

In [5]:
df = get_adzuna_jobs("gb", "accountant")
df.to_csv("data/post_ai/adzuna/accountant_gb.csv", index=False)

df = get_adzuna_jobs("de", "accountant")
df.to_csv("data/post_ai/adzuna/accountant_de.csv", index=False)

df = get_adzuna_jobs("nl", "accountant")
df.to_csv("data/post_ai/adzuna/accountant_nl.csv", index=False)

In [6]:
df = get_adzuna_jobs("gb", "business analyst")
df.to_csv("data/post_ai/adzuna/business_analyst_gb.csv", index=False)

df = get_adzuna_jobs("de", "business analyst")
df.to_csv("data/post_ai/adzuna/business_analyst_de.csv", index=False)

df = get_adzuna_jobs("nl", "business analyst")
df.to_csv("data/post_ai/adzuna/business_analyst_nl.csv", index=False)

In [7]:
df = get_adzuna_jobs("gb", "data analyst")
df.to_csv("data/post_ai/adzuna/data_analyst_gb.csv", index=False)

df = get_adzuna_jobs("de", "data analyst")
df.to_csv("data/post_ai/adzuna/data_analyst_de.csv", index=False)

df = get_adzuna_jobs("nl", "data analyst")
df.to_csv("data/post_ai/adzuna/data_analyst_nl.csv", index=False)

In [8]:
df = get_adzuna_jobs("gb", "software engineer")
df.to_csv("data/post_ai/adzuna/software_engineer_gb.csv", index=False)

df = get_adzuna_jobs("de", "software engineer")
df.to_csv("data/post_ai/adzuna/software_engineer_de.csv", index=False)

df = get_adzuna_jobs("nl", "software engineer")
df.to_csv("data/post_ai/adzuna/software_engineer_nl.csv", index=False)

# cleaning

In [9]:
import pandas as pd

def clean_adzuna(df):
    df = df.rename(columns={
        "title": "job_title",
        "job_title": "job_title",
        "description": "job_description",
        "job_description": "job_description",
        "created": "date_posted",
        "country": "country"
    })

    df["source"] = "adzuna"

    keep = ["job_title", "job_description", "country", "date_posted", "source"]
    df = df[[c for c in keep if c in df.columns]]

    return df

In [10]:
df = pd.read_csv("data/post_ai/adzuna/accountant_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_accountant_gb.csv", index=False)

In [11]:
df = pd.read_csv("data/post_ai/adzuna/accountant_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_accountant_de.csv", index=False)

In [12]:
df = pd.read_csv("data/post_ai/adzuna/accountant_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_accountant_nl.csv", index=False)

In [13]:
df = pd.read_csv("data/post_ai/adzuna/business_analyst_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_business_analyst_gb.csv", index=False)

In [14]:
df = pd.read_csv("data/post_ai/adzuna/business_analyst_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_business_analyst_de.csv", index=False)

In [15]:
df = pd.read_csv("data/post_ai/adzuna/business_analyst_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_business_analyst_nl.csv", index=False)

In [16]:
df = pd.read_csv("data/post_ai/adzuna/data_analyst_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_data_analyst_gb.csv", index=False)

In [17]:
df = pd.read_csv("data/post_ai/adzuna/data_analyst_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_data_analyst_de.csv", index=False)

In [18]:
df = pd.read_csv("data/post_ai/adzuna/data_analyst_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_data_analyst_nl.csv", index=False)

In [19]:
df = pd.read_csv("data/post_ai/adzuna/software_engineer_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_software_engineer_gb.csv", index=False)

In [20]:
df = pd.read_csv("data/post_ai/adzuna/software_engineer_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_software_engineer_de.csv", index=False)

In [21]:
df = pd.read_csv("data/post_ai/adzuna/software_engineer_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_software_engineer_nl.csv", index=False)

In [22]:
import glob

files = glob.glob("data/post_ai/adzuna/*")
files

['data/post_ai/adzuna/accountant_gb.csv',
 'data/post_ai/adzuna/cleaned_accountant_de.csv',
 'data/post_ai/adzuna/cleaned_software_engineer_nl.csv',
 'data/post_ai/adzuna/cleaned_business_analyst_nl.csv',
 'data/post_ai/adzuna/business_analyst_gb.csv',
 'data/post_ai/adzuna/cleaned_data_analyst_de.csv',
 'data/post_ai/adzuna/data_analyst_nl.csv',
 'data/post_ai/adzuna/cleaned_software_engineer_gb.csv',
 'data/post_ai/adzuna/cleaned_business_analyst_de.csv',
 'data/post_ai/adzuna/cleaned_software_engineer_de.csv',
 'data/post_ai/adzuna/cleaned_data_analyst_gb.csv',
 'data/post_ai/adzuna/accountant_nl.csv',
 'data/post_ai/adzuna/cleaned_accountant_gb.csv',
 'data/post_ai/adzuna/software_engineer_nl.csv',
 'data/post_ai/adzuna/cleaned_accountant_nl.csv',
 'data/post_ai/adzuna/cleaned_business_analyst_gb.csv',
 'data/post_ai/adzuna/data_analyst_gb.csv',
 'data/post_ai/adzuna/software_engineer_gb.csv',
 'data/post_ai/adzuna/cleaned_data_analyst_nl.csv',
 'data/post_ai/adzuna/data_analyst_de.csv',
 'data/post_ai/adzuna/business_analyst_de.csv',
 'data/post_ai/adzuna/software_engineer_de.csv',
 'data/post_ai/adzuna/accountant_de.csv',
 'data/post_ai/adzuna/business_analyst_nl.csv']

In [23]:
import pandas as pd
import glob

cleaned_files = glob.glob("data/post_ai/adzuna/cleaned_*.csv")

for f in cleaned_files:
    print(f"\n--- Preview of {f} ---")
    df = pd.read_csv(f)
    print(df.head(5))

--- Preview of data/post_ai/adzuna/cleaned_accountant_de.csv ---
                   job_title  \
0  Senior Accountant (m/w/d)
1  Senior Accountant (m/w/d)
2  Senior Accountant (m/w/d)
3  Senior Accountant (m/w/d)
4     Tax Accountant (m/w/d)

                                     job_description country  \
0  Trek ist ein fantastischer Arbeitgeber mit tol...      de
1  Als Projektentwickler und Bauträger und Teil d...      de
2  Die Michels Trenchless GmbH in Wiesbaden ist T...      de
3  Als eines der weltweit führenden Dentalunterne...      de
4  Sie möchten in einem international agierenden ...      de

            date_posted  source
0  2026-02-23T18:30:58Z  adzuna
1  2026-02-25T06:35:04Z  adzuna
2  2026-02-21T06:22:40Z  adzuna
3  2026-03-02T18:44:03Z  adzuna
4  2026-02-19T06:13:59Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_software_engineer_nl.csv ---
                job_title                                    job_description  \
0  Lead Software Engineer  Wil jij jouw ervaring inzetten om complexe dat...
1       Software Engineer  In het kort Drie redenen waarom deze vacature ...
2       Software Engineer  In het kort Drie redenen waarom deze vacature ...
3       Software Engineer  In het kort Drie redenen waarom deze vacature ...
4       Software Engineer  In het kort Drie redenen waarom deze vacature ...

  country           date_posted  source
0      nl  2026-02-23T11:41:04Z  adzuna
1      nl  2026-03-02T11:24:38Z  adzuna
2      nl  2026-03-02T11:24:38Z  adzuna
3      nl  2026-03-02T11:24:39Z  adzuna
4      nl  2026-03-02T11:24:39Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_business_analyst_nl.csv ---
                   job_title  \
0  Vacature Business Analyst
1           Business Analyst
2       Business analist SAP
3           Business Analyst
4           Business Analyst

                                     job_description country  \
0  Functieomschrijving: Heb jij een scherp analyt...      nl
1  Ben jij een echte Business Analist die energie...      nl
2  Als business analist/consultant speel je een c...      nl
3  Together we achieve more than alone: Our squad...      nl
4  We are looking for a Medior or Senior Business...      nl

            date_posted  source
0  2026-02-13T11:22:01Z  adzuna
1  2025-09-12T21:06:20Z  adzuna
2  2026-02-10T12:53:32Z  adzuna
3  2026-02-18T06:41:36Z  adzuna
4  2026-03-11T10:53:59Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_data_analyst_de.csv ---
                       job_title  \
0  Senior Marketing Data Analyst
1           Data Analyst (w/m/d)
2           Data Analyst (w/m/d)
3           Data Analyst (w/m/d)
4           Data Analyst (w/m/d)

                                     job_description country  \
0  N26 has reimagined banking for today's digital...      de
1  Willkommen bei KIND! Mit mehr als 3500 Mitarbe...      de
2  Willkommen bei KIND! Mit mehr als 3500 Mitarbe...      de
3  Willkommen bei KIND! Mit mehr als 3500 Mitarbe...      de
4  Willkommen bei KIND! Mit mehr als 3500 Mitarbe...      de

            date_posted  source
0  2026-03-13T06:46:27Z  adzuna
1  2026-01-08T19:14:08Z  adzuna
2  2026-01-07T03:12:36Z  adzuna
3  2026-01-08T19:14:08Z  adzuna
4  2026-01-08T19:14:08Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_software_engineer_gb.csv ---
            job_title                                    job_description  \
0   Software Engineer  DV Cleared Software Engineer (DBA / Data-Focus...
1   Software Engineer  Day Rate: £650  (Inside IR35) Contract Length:...
2  Software Engineers  Software Engineers Package - £55,000 - £85,000...
3   Software Engineer  Job Title: Mid-Level Software Engineer Locatio...
4   Software Engineer  We are looking for a highly motivated Software...

  country           date_posted  source
0      gb  2026-03-05T10:23:16Z  adzuna
1      gb  2026-02-01T11:22:05Z  adzuna
2      gb  2026-03-07T10:29:02Z  adzuna
3      gb  2026-02-27T14:27:24Z  adzuna
4      gb  2026-03-04T18:44:30Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_business_analyst_de.csv ---
                                           job_title  \
0                           Business Analyst (m/w/d)
1  Duales Studium Wirtschaftsinformatik B.Sc. – I...
2  ​​IT Business Analyst (m/w/d) Kundendaten und ...
3                        IT Business Analyst (m/w/d)
4               Technischer Business Analyst (m/w/d)

                                     job_description country  \
0  Als einer der größten Banken-IT-Dienstleister ...      de
1  Wir sind der Digitalisierungspartner in der ge...      de
2  Wir sind einer der größten Arbeitgeber in Müns...      de
3  Wir machen aus Sensorik Zukunft. Unsere Sensor...      de
4  Wir sind die Custom Software Solutions - eine ...      de

            date_posted  source
0  2026-03-13T06:46:38Z  adzuna
1  2026-02-17T18:07:04Z  adzuna
2  2026-03-13T06:48:11Z  adzuna
3  2026-02-27T06:33:28Z  adzuna
4  2026-03-13T06:46:39Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_software_engineer_de.csv ---
                                   job_title  \
0          Quantum Software Engineer (m/w/d)
1  (Senior) Software Engineer Oracle (w/m/d)
2     Lead Quantum Software Engineer (m/w/d)
3     Simulation & Software Engineer (m/w/d)
4          Quantum Software Engineer (m/w/d)

                                     job_description country  \
0  Mindestens 3 Jahre Berufserfahrung in der Soft...      de
1  Willkommen bei Rhenus! Die Rhenus Gruppe ist e...      de
2  Die Schwarz IT betreut die gesamte digitale In...      de
3  Sie möchten unter anderem die Detektion und An...      de
4  Die Schwarz IT betreut die gesamte digitale In...      de

            date_posted  source
0  2026-02-25T18:33:15Z  adzuna
1  2026-02-28T06:34:41Z  adzuna
2  2026-02-10T18:20:00Z  adzuna
3  2026-03-13T06:46:42Z  adzuna
4  2026-02-17T06:13:55Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_data_analyst_gb.csv ---
                              job_title  \
0  Data Analyst Trainee - job guarantee
1                          Data Analyst
2                          Data Analyst
3                  Data Analyst Trainee
4                          Data Analyst

                                     job_description country  \
0  Are you ready to start a new career in Data An...      gb
1  Data Analyst Gillingham, Kent Hybrid working D...      gb
2  A well-established business is looking for a D...      gb
3  Are you looking to benefit from a new career i...      gb
4  Data Analyst (SystmOne) Huddersfield 3 months ...      gb

            date_posted  source
0  2026-02-19T18:28:35Z  adzuna
1  2026-02-27T14:55:41Z  adzuna
2  2026-02-27T22:35:38Z  adzuna
3  2026-03-10T10:22:24Z  adzuna
4  2026-03-12T17:32:11Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_accountant_gb.csv ---
                                 job_title  \
0        Accountant - Accounts preparation
1  Accounts Manager (Qualified Accountant)
2                               Accountant
3                               Accountant
4                               Accountant

                                     job_description country  \
0  Accounts Preperation, Accountant, Accounts You...      gb
1  ACA/ACCA Accounts Manager job in Norwich – Div...      gb
2  Financial Accountant and Management Accountant...      gb
3  Accountant Your new company A well-established...      gb
4  Practice Accountant, Hereford, Up to £44,000 A...      gb

            date_posted  source
0  2026-02-24T10:27:17Z  adzuna
1  2026-02-24T10:27:25Z  adzuna
2  2026-02-24T10:27:24Z  adzuna
3  2026-02-24T10:27:23Z  adzuna
4  2026-02-24T10:27:21Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_accountant_nl.csv ---
                        job_title  \
0  Gevorderd assistent accountant
1            Assistant Accountant
2                   Accountant AA
3            Assistent Accountant
4            Assistent Accountant

                                     job_description country  \
0  Ben jij een ervaren assistent accountant met e...      nl
1  Wat je gaat doen Ben jij een gedreven professi...      nl
2  Ben jij (bijna) tekenbevoegd Accountant (AA), ...      nl
3  Heb jij een ondernemende instelling, zit je vo...      nl
4  Accent Accountants is opzoek naar een assisten...      nl

            date_posted  source
0  2026-03-02T11:24:57Z  adzuna
1  2025-12-18T08:49:56Z  adzuna
2  2026-03-02T11:24:33Z  adzuna
3  2026-03-02T11:24:25Z  adzuna
4  2026-03-02T11:24:26Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_business_analyst_gb.csv ---
                             job_title  \
0  Business Analyst (Renewable Energy)
1                     Business Analyst
2                     Business Analyst
3                     Business Analyst
4                     Business Analyst

                                     job_description country  \
0  A fast-growth Renewable Energy business in Lon...      gb
1  Business Analyst Location: SheffieldSalary:c£3...      gb
2  Business Analyst – Hull / Hybrid £45,000 - £50...      gb
3  Business Analyst / Product Owner (SaaS) The Op...      gb
4  Business Analyst, Harlow, Hybrid/Office £28,00...      gb

            date_posted  source
0  2026-02-24T10:27:27Z  adzuna
1  2026-03-05T23:35:13Z  adzuna
2  2026-02-27T14:26:12Z  adzuna
3  2026-02-27T14:58:09Z  adzuna
4  2026-02-27T14:29:59Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_data_analyst_nl.csv ---
                          job_title  \
0               Junior Data Analist
1                      Data Analist
2                      Data Analist
3                Data analist oti&t
4  Business Data Analist Operations

                                     job_description country  \
0  Sta je aan het begin van je carrière en wil je...      nl
1  Een baan boordevol: Verantwoordelijkheid: Je n...      nl
2  Een baan boordevol: Impact: Als data scientist...      nl
3  Jouw energie in de plus Als data analist binne...      nl
4  Word je meteen enthousiast als het gaat over r...      nl

            date_posted  source
0  2025-12-17T11:01:29Z  adzuna
1  2026-02-06T08:04:21Z  adzuna
2  2026-03-06T08:18:07Z  adzuna
3  2026-02-27T16:03:59Z  adzuna
4  2026-03-11T07:32:27Z  adzuna

In [24]:
df = pd.read_csv("data/post_ai/adzuna/cleaned_data_analyst_gb.csv")
df.head().T

,0,1,2,3,4
job_title,Data Analyst Trainee - job guarantee,Data Analyst,Data Analyst,Data Analyst Trainee,Data Analyst
job_description,Are you ready to start a new career in Data An...,"Data Analyst Gillingham, Kent Hybrid working D...",A well-established business is looking for a D...,Are you looking to benefit from a new career i...,Data Analyst (SystmOne) Huddersfield 3 months ...
country,gb,gb,gb,gb,gb
date_posted,2026-02-19T18:28:35Z,2026-02-27T14:55:41Z,2026-02-27T22:35:38Z,2026-03-10T10:22:24Z,2026-03-12T17:32:11Z
source,adzuna,adzuna,adzuna,adzuna,adzuna

In [25]:
import pandas as pd
import glob

# find all cleaned files
cleaned_files = glob.glob("data/post_ai/adzuna/cleaned_*.csv")

# load them into a list of DataFrames
dfs = [pd.read_csv(f) for f in cleaned_files]

# merge into one dataset
adzuna_post_ai = pd.concat(dfs, ignore_index=True)

# save the merged dataset
adzuna_post_ai.to_csv("data/post_ai/adzuna/adzuna_post_ai_merged.csv", index=False)

adzuna_post_ai.head()

,job_title,job_description,country,date_posted,source
0,Senior Accountant (m/w/d),Trek ist ein fantastischer Arbeitgeber mit tol...,de,2026-02-23T18:30:58Z,adzuna
1,Senior Accountant (m/w/d),Als Projektentwickler und Bauträger und Teil d...,de,2026-02-25T06:35:04Z,adzuna
2,Senior Accountant (m/w/d),Die Michels Trenchless GmbH in Wiesbaden ist T...,de,2026-02-21T06:22:40Z,adzuna
3,Senior Accountant (m/w/d),Als eines der weltweit führenden Dentalunterne...,de,2026-03-02T18:44:03Z,adzuna
4,Tax Accountant (m/w/d),Sie möchten in einem international agierenden ...,de,2026-02-19T06:13:59Z,adzuna

In [26]:
adzuna_post_ai.shape

(600, 5)

In [27]:
import pandas as pd

# load your merged dataset
df = pd.read_csv("data/post_ai/adzuna/adzuna_post_ai_merged.csv")

def assign_role(title):
    title_lower = str(title).lower()
    if "accountant" in title_lower:
        return "accountant"
    if "business analyst" in title_lower:
        return "business_analyst"
    if "data analyst" in title_lower:
        return "data_analyst"
    if "software engineer" in title_lower or "developer" in title_lower:
        return "software_engineer"
    return "unknown"

df["role"] = df["job_title"].apply(assign_role)

df.to_csv("data/post_ai/adzuna/adzuna_post_ai_with_roles.csv", index=False)

df.head(150)

,job_title,job_description,country,date_posted,source,role
0,Senior Accountant (m/w/d),Trek ist ein fantastischer Arbeitgeber mit tol...,de,2026-02-23T18:30:58Z,adzuna,accountant
1,Senior Accountant (m/w/d),Als Projektentwickler und Bauträger und Teil d...,de,2026-02-25T06:35:04Z,adzuna,accountant
2,Senior Accountant (m/w/d),Die Michels Trenchless GmbH in Wiesbaden ist T...,de,2026-02-21T06:22:40Z,adzuna,accountant
3,Senior Accountant (m/w/d),Als eines der weltweit führenden Dentalunterne...,de,2026-03-02T18:44:03Z,adzuna,accountant
4,Tax Accountant (m/w/d),Sie möchten in einem international agierenden ...,de,2026-02-19T06:13:59Z,adzuna,accountant
...,...,...,...,...,...,...
145,Security Business Analist,Position Description: Security Business Analis...,nl,2026-03-05T02:26:41Z,adzuna,unknown
146,Technical Business Analyst,Technical Business Analyst Who we are: You may...,nl,2026-03-06T02:10:31Z,adzuna,business_analyst
147,Business Analyst Logistics,Zet jij data om in daadkracht? Kom dan werken ...,nl,2026-03-09T02:40:28Z,adzuna,business_analyst
148,Agile Business Analist,Ben je een bruggenbouwer tussen business en IT...,nl,2026-02-18T03:58:40Z,adzuna,unknown
149,OneView Business analyst,"For an ongoing OneView implementation project,...",nl,2025-12-04T21:10:50Z,adzuna,business_analyst

In [28]:
df = pd.read_csv("data/post_ai/adzuna/adzuna_post_ai_with_roles.csv")
df["role"].value_counts()

role
accountant           148
software_engineer    148
business_analyst     127
data_analyst         111
unknown               66
Name: count, dtype: int64

In [29]:
df[df["role"] == "unknown"][["job_title"]].head(30)

                                             job_title
99                              Software Test Engineer
102                               Business analist SAP
106                                   Business Analist
107                                   Business analist
108                                   Business Analist
109                                   Business Analist
110                                   Business Analist
114                                   Business Analist
115                                   Business Analist
117                                   Business Analist
121                                   Business Analist
129                      Business Intelligence Analist
132                      Business Analist - Pancompany
133                            Senior Business Analist
135                   Business Analist Assetmanagement
136                       Traineeship Business Analist
138             Applicatiebeheerder / Business Analist
139                               BPM Business Analist
141                                Business Analist BI
143                                IT Business Analist
144                          Security Business Analist
145                          Security Business Analist
148                             Agile Business Analist
183         E-Commerce Data & Insights Analyst (m/w/d)
192                           Financial (Data) Analyst
251  Duales Studium Wirtschaftsinformatik B.Sc. – I...
324                  Tech Lead (m/w/d) Personalization
479                       Relatiebeheerder Accountancy
480           Belastingadviseur Vermogende Ondernemers
550                                Junior Data Analist

In [30]:
def assign_role(title):
    t = str(title).lower()

    # Accountant
    if "accountant" in t or "accounts assistant" in t or "finance assistant" in t:
        return "accountant"

    # Business Analyst
    if "business analyst" in t or "ba " in t or "business intelligence analyst" in t:
        return "business_analyst"

    # Data Analyst (English + Dutch + variants)
    if (
        "data analyst" in t or
        "data analist" in t or
        "data-analist" in t or
        "data governance" in t or
        "data operations" in t or
        "reporting analyst" in t or
        "bi analyst" in t or
        "analytics" in t
    ):
        return "data_analyst"

    # Software Engineer / Developer / Data Engineer
    if (
        "software engineer" in t or
        "developer" in t or
        "engineer" in t or
        "data engineer" in t or
        "full stack" in t or
        "backend" in t or
        "frontend" in t
    ):
        return "software_engineer"

    return "unknown"

In [31]:
df["role"] = df["job_title"].apply(assign_role)
df["role"].value_counts()

role
software_engineer    149
accountant           148
data_analyst         148
business_analyst     127
unknown               28
Name: count, dtype: int64

In [32]:
df[df["role"] == "unknown"]["job_title"].sample(20, random_state=42)

121                                     Business Analist
324                    Tech Lead (m/w/d) Personalization
117                                     Business Analist
148                               Agile Business Analist
102                                 Business analist SAP
133                              Senior Business Analist
141                                  Business Analist BI
183           E-Commerce Data & Insights Analyst (m/w/d)
132                        Business Analist - Pancompany
135                     Business Analist Assetmanagement
138               Applicatiebeheerder / Business Analist
106                                     Business Analist
109                                     Business Analist
110                                     Business Analist
107                                     Business analist
139                                 BPM Business Analist
192                             Financial (Data) Analyst
108                                     Business Analist
479                         Relatiebeheerder Accountancy
251    Duales Studium Wirtschaftsinformatik B.Sc. – I...
Name: job_title, dtype: object

In [33]:
def assign_role(title):
    t = str(title).lower()

    # Accountant (English + Dutch)
    if (
        "accountant" in t or
        "boekhoudkundig" in t or
        "accounts assistant" in t or
        "finance assistant" in t
    ):
        return "accountant"

    # Business Analyst (English + Dutch + German + variants)
    if (
        "business analyst" in t or
        "business analist" in t or
        "business-analist" in t or
        "business intelligence analist" in t or
        "business intelligence analyst" in t or
        "business it-analyst" in t or
        "business systems analyst" in t or
        "business applications" in t or
        "market analyst" in t or
        "analyst prozessdigitalisierung" in t or
        "business & market analyst" in t
    ):
        return "business_analyst"

    # Data Analyst (English + Dutch + German + variants)
    if (
        "data analyst" in t or
        "data analist" in t or
        "data-analist" in t or
        "data governance" in t or
        "data operations" in t or
        "reporting analyst" in t or
        "bi analyst" in t or
        "analytics" in t
    ):
        return "data_analyst"

    # Software Engineer / Developer / Data Engineer (English + German)
    if (
        "software engineer" in t or
        "developer" in t or
        "entwickler" in t or
        "engineer" in t or
        "data engineer" in t or
        "full stack" in t or
        "backend" in t or
        "frontend" in t
    ):
        return "software_engineer"

    return "unknown"

In [34]:
df["role"] = df["job_title"].apply(assign_role)
df["role"].value_counts()

role
software_engineer    149
business_analyst     149
accountant           148
data_analyst         148
unknown                6
Name: count, dtype: int64

In [35]:
df = df[df["role"] != "unknown"]
df.to_csv("data/post_ai/adzuna/adzuna_post_ai_final.csv", index=False)

In [36]:
import pandas as pd

uk = pd.read_csv("/content/UKJobPostings.csv")

uk = uk.rename(columns={
    "title": "job_title",
    "description": "job_description",
    "date": "date_posted",
    "location": "country"
})

uk["country"] = "gb"
uk["source"] = "kaggle_uk_2023_2025"

keep = ["job_title", "job_description", "country", "date_posted", "source"]
uk = uk[[c for c in keep if c in uk.columns]]

FileNotFoundError: [Errno 2] No such file or directory: '/content/UKJobPostings.csv'

In [ ]:
import pandas as pd

uk = pd.read_csv("/content/UKJobPostings.csv")


print("UK columns:", uk.columns.tolist())

In [ ]:
import pandas as pd

uk = pd.read_csv("/content/UKJobPostings.csv")

uk_clean = uk.rename(columns={
    "title": "job_title",
    "full_description": "job_description",
    "created": "date_posted",
    "location": "country"
})

# If full_description is missing, fall back to clean_text
uk_clean["job_description"] = uk_clean["job_description"].fillna(uk["clean_text"])

uk_clean["country"] = "gb"
uk_clean["source"] = "kaggle_uk_2023_2025"

keep = ["job_title", "job_description", "country", "date_posted", "source"]
uk_clean = uk_clean[keep]

In [ ]:
uk_clean["role"] = uk_clean["job_title"].apply(assign_role)

In [ ]:
uk_clean = uk_clean[uk_clean["role"] != "unknown"]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
adzuna_clean = pd.read_csv("/content/data/post_ai/adzuna/adzuna_post_ai_final.csv")

In [ ]:
uk_clean = pd.read_csv("/content/UKJobPostings.csv")

In [ ]:
adzuna_clean.head()
uk_clean.head()

In [ ]:
post_ai_full = pd.concat([adzuna_clean, uk_clean], ignore_index=True)

In [ ]:
post_ai_full.to_csv("/content/data/post_ai/post_ai_full.csv", index=False)

In [ ]:
post_ai_full.shape
post_ai_full["role"].value_counts()
post_ai_full["country"].value_counts()

In [ ]:
adzuna_clean.shape
uk_clean.shape
post_ai_full.shape

In [ ]:
post_ai_full[post_ai_full["job_title"].str.contains("cloud", case=False, na=False)].head()

In [ ]:
post_ai_full.isna().sum()

In [ ]:
post_ai_full = post_ai_full[[
    "job_title",
    "job_description",
    "country",
    "date_posted",
    "source",
    "role"
]]