<a href="https://colab.research.google.com/github/crystalclcm/JobPostings/blob/main/Post_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import requests
import pandas as pd

In [38]:
APP_ID = "90fb93ab"
APP_KEY = "ac0d74800544bfc63431a2d3747a92c5"

In [39]:
import os
os.makedirs("data/post_ai/adzuna", exist_ok=True)

In [40]:
import requests
import pandas as pd

APP_ID = "90fb93ab"
APP_KEY = "ac0d74800544bfc63431a2d3747a92c5"

def get_adzuna_jobs(country_code, role):
    url = f"https://api.adzuna.com/v1/api/jobs/{country_code}/search/1"
    params = {
        "app_id": APP_ID,
        "app_key": APP_KEY,
        "results_per_page": 50,
        "what": role
    }

    response = requests.get(url, params=params).json()
    results = response.get("results", [])

    rows = []
    for job in results:
        rows.append({
            "job_title": job.get("title"),
            "job_description": job.get("description"),
            "country": country_code,
            "date_posted": job.get("created"),
            "source": "adzuna"
        })

    return pd.DataFrame(rows)

In [41]:
df = get_adzuna_jobs("gb", "accountant")
df.to_csv("data/post_ai/adzuna/accountant_gb.csv", index=False)

df = get_adzuna_jobs("de", "accountant")
df.to_csv("data/post_ai/adzuna/accountant_de.csv", index=False)

df = get_adzuna_jobs("nl", "accountant")
df.to_csv("data/post_ai/adzuna/accountant_nl.csv", index=False)

In [42]:
df = get_adzuna_jobs("gb", "business analyst")
df.to_csv("data/post_ai/adzuna/business_analyst_gb.csv", index=False)

df = get_adzuna_jobs("de", "business analyst")
df.to_csv("data/post_ai/adzuna/business_analyst_de.csv", index=False)

df = get_adzuna_jobs("nl", "business analyst")
df.to_csv("data/post_ai/adzuna/business_analyst_nl.csv", index=False)

In [43]:
df = get_adzuna_jobs("gb", "data analyst")
df.to_csv("data/post_ai/adzuna/data_analyst_gb.csv", index=False)

df = get_adzuna_jobs("de", "data analyst")
df.to_csv("data/post_ai/adzuna/data_analyst_de.csv", index=False)

df = get_adzuna_jobs("nl", "data analyst")
df.to_csv("data/post_ai/adzuna/data_analyst_nl.csv", index=False)

In [44]:
df = get_adzuna_jobs("gb", "software engineer")
df.to_csv("data/post_ai/adzuna/software_engineer_gb.csv", index=False)

df = get_adzuna_jobs("de", "software engineer")
df.to_csv("data/post_ai/adzuna/software_engineer_de.csv", index=False)

df = get_adzuna_jobs("nl", "software engineer")
df.to_csv("data/post_ai/adzuna/software_engineer_nl.csv", index=False)

# cleaning

In [45]:
import pandas as pd

def clean_adzuna(df):
    df = df.rename(columns={
        "title": "job_title",
        "job_title": "job_title",
        "description": "job_description",
        "job_description": "job_description",
        "created": "date_posted",
        "country": "country"
    })

    df["source"] = "adzuna"

    keep = ["job_title", "job_description", "country", "date_posted", "source"]
    df = df[[c for c in keep if c in df.columns]]

    return df

In [46]:
df = pd.read_csv("data/post_ai/adzuna/accountant_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_accountant_gb.csv", index=False)

In [47]:
df = pd.read_csv("data/post_ai/adzuna/accountant_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_accountant_de.csv", index=False)

In [48]:
df = pd.read_csv("data/post_ai/adzuna/accountant_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_accountant_nl.csv", index=False)

In [49]:
df = pd.read_csv("data/post_ai/adzuna/business_analyst_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_business_analyst_gb.csv", index=False)

In [50]:
df = pd.read_csv("data/post_ai/adzuna/business_analyst_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_business_analyst_de.csv", index=False)

In [51]:
df = pd.read_csv("data/post_ai/adzuna/business_analyst_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_business_analyst_nl.csv", index=False)

In [52]:
df = pd.read_csv("data/post_ai/adzuna/data_analyst_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_data_analyst_gb.csv", index=False)

In [53]:
df = pd.read_csv("data/post_ai/adzuna/data_analyst_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_data_analyst_de.csv", index=False)

In [54]:
df = pd.read_csv("data/post_ai/adzuna/data_analyst_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_data_analyst_nl.csv", index=False)

In [55]:
df = pd.read_csv("data/post_ai/adzuna/software_engineer_gb.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_software_engineer_gb.csv", index=False)

In [56]:
df = pd.read_csv("data/post_ai/adzuna/software_engineer_de.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_software_engineer_de.csv", index=False)

In [57]:
df = pd.read_csv("data/post_ai/adzuna/software_engineer_nl.csv")
cleaned = clean_adzuna(df)
cleaned.to_csv("data/post_ai/adzuna/cleaned_software_engineer_nl.csv", index=False)

In [58]:
import glob

files = glob.glob("data/post_ai/adzuna/*")
files

['data/post_ai/adzuna/cleaned_accountant_gb.csv',
 'data/post_ai/adzuna/data_analyst_gb.csv',
 'data/post_ai/adzuna/software_engineer_nl.csv',
 'data/post_ai/adzuna/adzuna_post_ai_with_roles.csv',
 'data/post_ai/adzuna/cleaned_business_analyst_nl.csv',
 'data/post_ai/adzuna/cleaned_accountant_nl.csv',
 'data/post_ai/adzuna/cleaned_data_analyst_gb.csv',
 'data/post_ai/adzuna/cleaned_data_analyst_de.csv',
 'data/post_ai/adzuna/accountant_gb.csv',
 'data/post_ai/adzuna/cleaned_business_analyst_de.csv',
 'data/post_ai/adzuna/business_analyst_gb.csv',
 'data/post_ai/adzuna/data_analyst_nl.csv',
 'data/post_ai/adzuna/cleaned_business_analyst_gb.csv',
 'data/post_ai/adzuna/business_analyst_de.csv',
 'data/post_ai/adzuna/adzuna_post_ai_final.csv',
 'data/post_ai/adzuna/software_engineer_de.csv',
 'data/post_ai/adzuna/cleaned_software_engineer_gb.csv',
 'data/post_ai/adzuna/data_analyst_de.csv',
 'data/post_ai/adzuna/accountant_nl.csv',
 'data/post_ai/adzuna/cleaned_software_engineer_de.csv',
 'data/post_ai/adzuna/cleaned_software_engineer_nl.csv',
 'data/post_ai/adzuna/accountant_de.csv',
 'data/post_ai/adzuna/cleaned_accountant_de.csv',
 'data/post_ai/adzuna/cleaned_data_analyst_nl.csv',
 'data/post_ai/adzuna/software_engineer_gb.csv',
 'data/post_ai/adzuna/business_analyst_nl.csv',
 'data/post_ai/adzuna/adzuna_post_ai_merged.csv']

In [59]:
import pandas as pd
import glob

cleaned_files = glob.glob("data/post_ai/adzuna/cleaned_*.csv")

for f in cleaned_files:
    print(f"\n--- Preview of {f} ---")
    df = pd.read_csv(f)
    print(df.head(5))

--- Preview of data/post_ai/adzuna/cleaned_accountant_gb.csv ---
                                  job_title  \
0  Chartered Accountant -Accounts and Audit
1   Accounts Manager (Qualified Accountant)
2                                Accountant
3                                Accountant
4                                Accountant

                                     job_description country  \
0  Join a strategic accounting, tax and business ...      gb
1  ACA/ACCA Accounts Manager job in Norwich – Div...      gb
2  Financial Accountant and Management Accountant...      gb
3  Accountant Your new company A well-established...      gb
4  Accountant in Haverfordwest Your new company A...      gb

            date_posted  source
0  2026-02-24T10:27:12Z  adzuna
1  2026-02-24T10:27:25Z  adzuna
2  2026-02-24T10:27:24Z  adzuna
3  2026-02-24T10:27:23Z  adzuna
4  2026-02-24T10:27:13Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_business_analyst_nl.csv ---
                                           job_title  \
0                                   Business Analyst
1                          Vacature Business Analyst
2                               Business analist SAP
3  Business/data-analist Commandopost Vastgoed(61...
4                                   Business Analist

                                     job_description country  \
0  Ben jij een echte Business Analist die energie...      nl
1  Functieomschrijving: Heb jij een scherp analyt...      nl
2  Als business analist/consultant speel je een c...      nl
3  Vacature kenmerken Standplaats Den Haag Contra...      nl
4  Voor Uitvoeringsinstituut Werknemersverzekerin...      nl

            date_posted  source
0  2025-09-12T21:06:20Z  adzuna
1  2026-02-13T11:22:01Z  adzuna
2  2026-02-10T12:53:32Z  adzuna
3  2026-03-06T16:00:09Z  adzuna
4  2026-03-07T05:48:45Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_accountant_nl.csv ---
                          job_title  \
0              Assistent Accountant
1  Zelfstandig Assistent Accountant
2    Gevorderd Assistent Accountant
3       Junior Assistent Accountant
4              Assistent accountant

                                     job_description country  \
0  Ben jij onze nieuwe bevlogen, energieke en gem...      nl
1  Word jij enthousiast van een afwisselende baan...      nl
2  De accountancywereld kent voor jou geen geheim...      nl
3  Ben jij een enthousiaste administratieve duize...      nl
4  Over ons R&R Administratiekantoor is een klein...      nl

            date_posted  source
0  2026-03-02T11:24:52Z  adzuna
1  2026-03-02T11:24:52Z  adzuna
2  2026-03-02T11:24:52Z  adzuna
3  2026-03-02T11:24:52Z  adzuna
4  2026-01-23T19:09:51Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_data_analyst_gb.csv ---
      job_title                                    job_description country  \
0  Data Analyst  Data Analyst Gillingham, Kent Hybrid working D...      gb
1  Data Analyst  Data Analyst London/Hybrid £40,000-£45,000 Are...      gb
2  Data Analyst  A well-established business is looking for a D...      gb
3  Data Analyst  Role: Data Analyst Location: West Wales Salary...      gb
4  Data Analyst  Data Analyst (WooCommerce & Klaviyo) – Inside ...      gb

            date_posted  source
0  2026-02-27T14:55:41Z  adzuna
1  2026-02-27T18:25:06Z  adzuna
2  2026-02-27T22:35:38Z  adzuna
3  2026-02-27T14:31:32Z  adzuna
4  2026-02-27T14:57:20Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_data_analyst_de.csv ---
                                     job_title  \
0                         Data Analyst (m/w/d)
1  Senior Data Engineer / Data Analyst (w/m/d)
2         Junior Customer Data Analyst (w/m/d)
3                         Data Analyst (w/m/d)
4                         Data Analyst (w/m/d)

                                     job_description country  \
0  Gastivo ist die führende B2B-Plattform in der ...      de
1  Das Universitätsklinikum Tübingen ist ein führ...      de
2  Wir sind die OUTLETCITY AG – Betreiber der Out...      de
3  Willkommen bei KIND! Mit mehr als 3500 Mitarbe...      de
4  Willkommen bei KIND! Mit mehr als 3500 Mitarbe...      de

            date_posted  source
0  2026-03-08T06:48:02Z  adzuna
1  2026-03-06T18:42:48Z  adzuna
2  2026-03-08T06:47:51Z  adzuna
3  2026-01-08T19:14:08Z  adzuna
4  2026-01-08T19:14:08Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_business_analyst_de.csv ---
                                           job_title  \
0                  (Senior) Business Analyst (w/m/d)
1                       Business Analyst CRM (m/w/d)
2  Senior Business Analyst:in (m/w/d) Risikomanag...
3  (Senior) Business Analyst Commercial Analytics...
4  Duales Studium Wirtschaftsinformatik B.Sc. – I...

                                     job_description country  \
0  Die VHV Gruppe ist ein gewachsener Konzern von...      de
1  Im CRM-Team gestaltest du die Weiterentwicklun...      de
2  Faire Arbeitsbedingungen am Bau schaffen, Urla...      de
3  Wir bei The Stepstone Group haben eine klare u...      de
4  Wir sind der Digitalisierungspartner in der ge...      de

            date_posted  source
0  2026-03-06T18:42:49Z  adzuna
1  2026-03-07T18:46:55Z  adzuna
2  2026-02-26T06:33:14Z  adzuna
3  2026-02-10T18:20:14Z  adzuna
4  2026-02-17T18:07:04Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_business_analyst_gb.csv ---
                             job_title  \
0  Business Analyst (Renewable Energy)
1                     Business Analyst
2                     Business Analyst
3                     Business Analyst
4                     Business Analyst

                                     job_description country  \
0  A fast-growth Renewable Energy business in Lon...      gb
1  BUSINESS ANALYST – IRESS EXPERIENCE (CONTRACT)...      gb
2  Business Analyst | Manchester (Onsite) | Up to...      gb
3  Business Analyst – Hull / Hybrid £45,000 - £50...      gb
4  Business Analyst / Product Owner (SaaS) The Op...      gb

            date_posted  source
0  2026-02-24T10:27:27Z  adzuna
1  2026-02-27T14:57:13Z  adzuna
2  2026-02-27T14:56:52Z  adzuna
3  2026-02-27T14:26:12Z  adzuna
4  2026-02-27T14:58:09Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_software_engineer_gb.csv ---
            job_title                                    job_description  \
0   Software Engineer  Job Description Software Engineer, Salesforce ...
1   Software Engineer  Day Rate: £650  (Inside IR35) Contract Length:...
2  Software Engineers  Software Engineers Package - £55,000 - £85,000...
3   Software Engineer  Pay up to £59,813, plus 28.97% employer pensio...
4   Software Engineer  Software Engineer - Defence / Search & Rescue ...

  country           date_posted  source
0      gb  2026-03-01T10:12:13Z  adzuna
1      gb  2026-02-01T11:22:05Z  adzuna
2      gb  2026-03-07T10:29:02Z  adzuna
3      gb  2026-03-07T06:56:36Z  adzuna
4      gb  2026-03-04T18:45:18Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_software_engineer_de.csv ---
                                       job_title  \
0              Quantum Software Engineer (m/w/d)
1         Lead Quantum Software Engineer (m/w/d)
2      (Senior) Software Engineer Oracle (w/m/d)
3              Quantum Software Engineer (m/w/d)
4  Software Engineer - Process Assurance (m/w/d)

                                     job_description country  \
0  Mindestens 3 Jahre Berufserfahrung in der Soft...      de
1  Die Schwarz IT betreut die gesamte digitale In...      de
2  Willkommen bei Rhenus! Die Rhenus Gruppe ist e...      de
3  Die Schwarz IT betreut die gesamte digitale In...      de
4  Akkodis ist ein globales Beratungsunternehmen ...      de

            date_posted  source
0  2026-02-25T18:33:15Z  adzuna
1  2026-02-10T18:20:00Z  adzuna
2  2026-02-28T06:34:41Z  adzuna
3  2026-02-17T06:13:55Z  adzuna
4  2026-03-08T06:48:09Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_software_engineer_nl.csv ---
                job_title                                    job_description  \
0       Software Engineer  In het kort Drie redenen waarom deze vacature ...
1       Software Engineer  In het kort Drie redenen waarom deze vacature ...
2       Software Engineer  In het kort Drie redenen waarom deze vacature ...
3       Software Engineer  In het kort Drie redenen waarom deze vacature ...
4  Lead Software Engineer  Wil jij jouw ervaring inzetten om complexe dat...

  country           date_posted  source
0      nl  2026-03-02T11:24:38Z  adzuna
1      nl  2026-03-02T11:24:39Z  adzuna
2      nl  2026-03-02T11:24:39Z  adzuna
3      nl  2026-03-02T11:24:39Z  adzuna
4      nl  2026-02-23T11:41:04Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_accountant_de.csv ---
                       job_title  \
0           Financial Accountant
1  Buchhalter/Accountant (m/w/d)
2  Buchhalter/Accountant (m/w/d)
3    Creditor Accountant (m/w/d)
4   Financial Accountant (m/w/d)

                                     job_description country  \
0  Imagine working at a company whose ultimate mi...      de
1  Die SACO Shipping GmbH entwickelt als Dienstle...      de
2  Was wir versprechen – das halten wir! Wir arbe...      de
3  Wir sind ein multikulturelles internationales ...      de
4  Exaktera ist ein Portfolio-Unternehmen von Uni...      de

            date_posted  source
0  2026-02-28T06:34:46Z  adzuna
1  2026-03-08T06:47:44Z  adzuna
2  2026-03-08T06:47:42Z  adzuna
3  2026-03-08T06:48:11Z  adzuna
4  2026-03-08T06:47:52Z  adzuna

--- Preview of data/post_ai/adzuna/cleaned_data_analyst_nl.csv ---
                  job_title  \
0              Data analist
1  Behavioural Data Analist
2       Junior Data Analist
3              Data Analist
4              Data Analist

                                     job_description country  \
0  Vacature kenmerken Standplaats Utrecht Contrac...      nl
1  Vacature kenmerken Standplaats Amsterdam Contr...      nl
2  Sta je aan het begin van je carrière en wil je...      nl
3  Een baan boordevol: Verantwoordelijkheid: Je n...      nl
4  Een baan boordevol: Impact: Als data scientist...      nl

            date_posted  source
0  2026-03-07T14:44:32Z  adzuna
1  2026-03-07T14:44:31Z  adzuna
2  2025-12-17T11:01:29Z  adzuna
3  2026-02-06T08:04:21Z  adzuna
4  2026-03-06T08:18:07Z  adzuna

In [60]:
df = pd.read_csv("data/post_ai/adzuna/cleaned_data_analyst_gb.csv")
df.head().T

,0,1,2,3,4
job_title,Data Analyst,Data Analyst,Data Analyst,Data Analyst,Data Analyst
job_description,"Data Analyst Gillingham, Kent Hybrid working D...","Data Analyst London/Hybrid £40,000-£45,000 Are...",A well-established business is looking for a D...,Role: Data Analyst Location: West Wales Salary...,Data Analyst (WooCommerce & Klaviyo) – Inside ...
country,gb,gb,gb,gb,gb
date_posted,2026-02-27T14:55:41Z,2026-02-27T18:25:06Z,2026-02-27T22:35:38Z,2026-02-27T14:31:32Z,2026-02-27T14:57:20Z
source,adzuna,adzuna,adzuna,adzuna,adzuna

In [61]:
import pandas as pd
import glob

# find all cleaned files
cleaned_files = glob.glob("data/post_ai/adzuna/cleaned_*.csv")

# load them into a list of DataFrames
dfs = [pd.read_csv(f) for f in cleaned_files]

# merge into one dataset
adzuna_post_ai = pd.concat(dfs, ignore_index=True)

# save the merged dataset
adzuna_post_ai.to_csv("data/post_ai/adzuna/adzuna_post_ai_merged.csv", index=False)

adzuna_post_ai.head()

,job_title,job_description,country,date_posted,source
0,Chartered Accountant -Accounts and Audit,"Join a strategic accounting, tax and business ...",gb,2026-02-24T10:27:12Z,adzuna
1,Accounts Manager (Qualified Accountant),ACA/ACCA Accounts Manager job in Norwich – Div...,gb,2026-02-24T10:27:25Z,adzuna
2,Accountant,Financial Accountant and Management Accountant...,gb,2026-02-24T10:27:24Z,adzuna
3,Accountant,Accountant Your new company A well-established...,gb,2026-02-24T10:27:23Z,adzuna
4,Accountant,Accountant in Haverfordwest Your new company A...,gb,2026-02-24T10:27:13Z,adzuna

In [62]:
adzuna_post_ai.shape

(600, 5)

In [63]:
import pandas as pd

# load your merged dataset
df = pd.read_csv("data/post_ai/adzuna/adzuna_post_ai_merged.csv")

def assign_role(title):
    title_lower = str(title).lower()
    if "accountant" in title_lower:
        return "accountant"
    if "business analyst" in title_lower:
        return "business_analyst"
    if "data analyst" in title_lower:
        return "data_analyst"
    if "software engineer" in title_lower or "developer" in title_lower:
        return "software_engineer"
    return "unknown"

df["role"] = df["job_title"].apply(assign_role)

df.to_csv("data/post_ai/adzuna/adzuna_post_ai_with_roles.csv", index=False)

df.head(150)

,job_title,job_description,country,date_posted,source,role
0,Chartered Accountant -Accounts and Audit,"Join a strategic accounting, tax and business ...",gb,2026-02-24T10:27:12Z,adzuna,accountant
1,Accounts Manager (Qualified Accountant),ACA/ACCA Accounts Manager job in Norwich – Div...,gb,2026-02-24T10:27:25Z,adzuna,accountant
2,Accountant,Financial Accountant and Management Accountant...,gb,2026-02-24T10:27:24Z,adzuna,accountant
3,Accountant,Accountant Your new company A well-established...,gb,2026-02-24T10:27:23Z,adzuna,accountant
4,Accountant,Accountant in Haverfordwest Your new company A...,gb,2026-02-24T10:27:13Z,adzuna,accountant
...,...,...,...,...,...,...
145,Accountant,Voor onze opdrachtgever (pharma industrie) zij...,nl,2026-01-26T22:49:54Z,adzuna,accountant
146,Accountant,Bij ZMS Accountancy beheer je je eigen klanten...,nl,2026-01-30T08:52:36Z,adzuna,accountant
147,Accountant,"Ben jij een ervaren, nauwkeurige professional ...",nl,2026-02-16T22:45:48Z,adzuna,accountant
148,Accountant,Our client is an independent corporate service...,nl,2025-03-13T10:53:52Z,adzuna,accountant
149,Accountant,Functieomschrijving Zoek jij een rol waarin je...,nl,2026-02-27T18:36:22Z,adzuna,accountant

In [64]:
df = pd.read_csv("data/post_ai/adzuna/adzuna_post_ai_with_roles.csv")
df["role"].value_counts()

role
accountant           147
software_engineer    144
business_analyst     117
data_analyst         108
unknown               84
Name: count, dtype: int64

In [65]:
df[df["role"] == "unknown"][["job_title"]].head(30)

                                            job_title
34                                  Account Executive
52                               Business analist SAP
53  Business/data-analist Commandopost Vastgoed(61...
54                                   Business Analist
57                             Business Analist Zoekt
58                                   Business Analist
59                                   Business Analist
60                                   Business analist
61                                   Business Analist
62                                   Business Analist
63                                   Business Analist
64                                   Business Analist
65                                   Business Analist
68                                   Business Analist
71                                   Business Analist
73                                   Business Analist
74                                   Business Analist
77                                   Business Analist
78                                   Business Analist
85                      Business Intelligence Analist
89                      Business Analist - Pancompany
91                   Business Analist Assetmanagement
92                                Business Analist IT
93                       Traineeship Business Analist
94                                Business Analist IT
95                          Business Analist Software
96                       Business Analist Informatica
97                          Business Analist Payments
98                            Business Analist Senior
99                        Business Analist ServiceNow

In [66]:
def assign_role(title):
    t = str(title).lower()

    # Accountant
    if "accountant" in t or "accounts assistant" in t or "finance assistant" in t:
        return "accountant"

    # Business Analyst
    if "business analyst" in t or "ba " in t or "business intelligence analyst" in t:
        return "business_analyst"

    # Data Analyst (English + Dutch + variants)
    if (
        "data analyst" in t or
        "data analist" in t or
        "data-analist" in t or
        "data governance" in t or
        "data operations" in t or
        "reporting analyst" in t or
        "bi analyst" in t or
        "analytics" in t
    ):
        return "data_analyst"

    # Software Engineer / Developer / Data Engineer
    if (
        "software engineer" in t or
        "developer" in t or
        "engineer" in t or
        "data engineer" in t or
        "full stack" in t or
        "backend" in t or
        "frontend" in t
    ):
        return "software_engineer"

    return "unknown"

In [67]:
df["role"] = df["job_title"].apply(assign_role)
df["role"].value_counts()

role
data_analyst         150
accountant           147
software_engineer    146
business_analyst     117
unknown               40
Name: count, dtype: int64

In [68]:
df[df["role"] == "unknown"]["job_title"].sample(20, random_state=42)

89                         Business Analist - Pancompany
77                                      Business Analist
74                                      Business Analist
97                             Business Analist Payments
58                                      Business Analist
68                                      Business Analist
420                    Senior Software En­gineer (m/w/d)
98                               Business Analist Senior
440    SAP ABAP OO Entwickler (S/4HANA) – Banking & R...
60                                      Business analist
96                          Business Analist Informatica
63                                      Business Analist
71                                      Business Analist
239           E-Commerce Data & Insights Analyst (m/w/d)
282    (Senior) Business & Commercial Controlling Ana...
62                                      Business Analist
78                                      Business Analist
95                             Business Analist Software
34                                     Account Executive
278                 (Senior) Business IT-Analyst (m/w/d)
Name: job_title, dtype: object

In [69]:
def assign_role(title):
    t = str(title).lower()

    # Accountant (English + Dutch)
    if (
        "accountant" in t or
        "boekhoudkundig" in t or
        "accounts assistant" in t or
        "finance assistant" in t
    ):
        return "accountant"

    # Business Analyst (English + Dutch + German + variants)
    if (
        "business analyst" in t or
        "business analist" in t or
        "business-analist" in t or
        "business intelligence analist" in t or
        "business intelligence analyst" in t or
        "business it-analyst" in t or
        "business systems analyst" in t or
        "business applications" in t or
        "market analyst" in t or
        "analyst prozessdigitalisierung" in t or
        "business & market analyst" in t
    ):
        return "business_analyst"

    # Data Analyst (English + Dutch + German + variants)
    if (
        "data analyst" in t or
        "data analist" in t or
        "data-analist" in t or
        "data governance" in t or
        "data operations" in t or
        "reporting analyst" in t or
        "bi analyst" in t or
        "analytics" in t
    ):
        return "data_analyst"

    # Software Engineer / Developer / Data Engineer (English + German)
    if (
        "software engineer" in t or
        "developer" in t or
        "entwickler" in t or
        "engineer" in t or
        "data engineer" in t or
        "full stack" in t or
        "backend" in t or
        "frontend" in t
    ):
        return "software_engineer"

    return "unknown"

In [70]:
df["role"] = df["job_title"].apply(assign_role)
df["role"].value_counts()

role
data_analyst         150
accountant           147
business_analyst     147
software_engineer    147
unknown                9
Name: count, dtype: int64

In [71]:
df = df[df["role"] != "unknown"]
df.to_csv("data/post_ai/adzuna/adzuna_post_ai_final.csv", index=False)

In [75]:
import pandas as pd

uk = pd.read_csv("/content/UKJobPostings.csv")

uk = uk.rename(columns={
    "title": "job_title",
    "description": "job_description",
    "date": "date_posted",
    "location": "country"
})

uk["country"] = "gb"
uk["source"] = "kaggle_uk_2023_2025"

keep = ["job_title", "job_description", "country", "date_posted", "source"]
uk = uk[[c for c in keep if c in uk.columns]]

In [76]:
import pandas as pd

uk = pd.read_csv("/content/UKJobPostings.csv")


print("UK columns:", uk.columns.tolist())

UK columns: ['id', 'title', 'company', 'location', 'salary_min', 'salary_max', 'created', 'category', 'contract_type', 'contract_time', 'home_url', 'full_description', 'domain', 'clean_text', 'title_tokens', 'text_tokens', 'location_tokens', 'title_role', 'family_role', 'seniority', 'skills_list', 'industry', 'salary_avg']

In [77]:
import pandas as pd

uk = pd.read_csv("/content/UKJobPostings.csv")

uk_clean = uk.rename(columns={
    "title": "job_title",
    "full_description": "job_description",
    "created": "date_posted",
    "location": "country"
})

# If full_description is missing, fall back to clean_text
uk_clean["job_description"] = uk_clean["job_description"].fillna(uk["clean_text"])

uk_clean["country"] = "gb"
uk_clean["source"] = "kaggle_uk_2023_2025"

keep = ["job_title", "job_description", "country", "date_posted", "source"]
uk_clean = uk_clean[keep]

In [78]:
uk_clean["role"] = uk_clean["job_title"].apply(assign_role)

In [79]:
uk_clean = uk_clean[uk_clean["role"] != "unknown"]

In [80]:
import pandas as pd
import numpy as np

In [81]:
adzuna_clean = pd.read_csv("/content/data/post_ai/adzuna/adzuna_post_ai_final.csv")

In [83]:
uk_clean = pd.read_csv("/content/UKJobPostings.csv")

In [84]:
adzuna_clean.head()
uk_clean.head()

,id,title,company,location,salary_min,salary_max,created,category,contract_type,contract_time,...,clean_text,title_tokens,text_tokens,location_tokens,title_role,family_role,seniority,skills_list,industry,salary_avg
0,4802556162,cloud data engineer,VM2R Services,"Bristol, South West England",46760.60,46760.60,2024-07-31T15:07:35Z,IT Jobs,NaN,NaN,...,"cloud data engineer VM2R Services Bristol, Sou...","['cloud', 'data', 'engineer']","['cloud', 'data', 'engineer', 'vm2r', 'service...","['bristol', 'south', 'west', 'england']",data engineer,engineer,other,[],[],46760.60
1,5417222782,cloud data engineer clickstream,FDJ UNITED,"Wimbledon, South West London",63267.14,63267.14,2025-09-27T11:19:27Z,IT Jobs,permanent,full_time,...,cloud data engineer clickstream FDJ UNITED Wim...,"['cloud', 'data', 'engineer', 'clickstream']","['cloud', 'data', 'engineer', 'clickstream', '...","['wimbledon', 'south', 'west', 'london']",data engineer,engineer,senior,"['python', 'sql', 'spark', 'kafka', 'airflow',...",['media_marketing'],63267.14
2,5415000387,machine learning engineer,SGI,UK,64209.18,64209.18,2025-09-26T13:11:26Z,IT Jobs,NaN,NaN,...,machine learning engineer SGI UK machine learn...,"['machine', 'learning', 'engineer']","['machine', 'learning', 'engineer', 'sgi', 'uk...",['uk'],machine learning engineer,engineer,intern,"['python', 'tensorflow', 'pytorch', 'deep_lear...",[],64209.18
3,5402258115,machine learning engineer,Markerstudy Insurance Services,"Manchester Science Park, Manchester",50869.80,50869.80,2025-09-16T23:53:25Z,IT Jobs,permanent,full_time,...,machine learning engineer Markerstudy Insuranc...,"['machine', 'learning', 'engineer']","['machine', 'learning', 'engineer', 'markerstu...","['manchester', 'science', 'park', 'manchester']",machine learning engineer,engineer,mid,"['python', 'r', 'etl', 'aws', 'azure', 'gcp', ...",['finance'],50869.80
4,5380549237,machine learning engineer,Gerrard White,"Manchester, Greater Manchester",42990.55,42990.55,2025-09-03T01:10:09Z,IT Jobs,NaN,NaN,...,machine learning engineer Gerrard White Manche...,"['machine', 'learning', 'engineer']","['machine', 'learning', 'engineer', 'gerrard',...","['manchester', 'greater', 'manchester']",machine learning engineer,engineer,mid,"['python', 'r', 'etl', 'aws', 'azure', 'gcp', ...",['finance'],42990.55

In [85]:
post_ai_full = pd.concat([adzuna_clean, uk_clean], ignore_index=True)

In [86]:
post_ai_full.to_csv("/content/data/post_ai/post_ai_full.csv", index=False)

In [87]:
post_ai_full.shape
post_ai_full["role"].value_counts()
post_ai_full["country"].value_counts()

country
gb    199
nl    198
de    194
Name: count, dtype: int64

In [88]:
adzuna_clean.shape
uk_clean.shape
post_ai_full.shape

(2876, 29)

In [89]:
post_ai_full[post_ai_full["job_title"].str.contains("cloud", case=False, na=False)].head()

,job_title,job_description,country,date_posted,source,role,id,title,company,location,...,clean_text,title_tokens,text_tokens,location_tokens,title_role,family_role,seniority,skills_list,industry,salary_avg
226,Data Analyst als Senior Consultant SAP Analyti...,"Dein Team Du hast Freude an Innovationen, span...",de,2026-01-08T19:14:08Z,adzuna,data_analyst,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
227,Data Analyst als Senior Consultant SAP Analyti...,"Dein Team Du hast Freude an Innovationen, span...",de,2026-01-08T19:14:09Z,adzuna,data_analyst,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
228,Data Analyst als Senior Consultant SAP Analyti...,"Dein Team Du hast Freude an Innovationen, span...",de,2026-01-08T19:14:08Z,adzuna,data_analyst,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,Data Analyst als Senior Consultant SAP Analyti...,"Dein Team Du hast Freude an Innovationen, span...",de,2026-01-08T19:14:09Z,adzuna,data_analyst,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,Data Analyst als Senior Consultant SAP Analyti...,"Dein Team Du hast Freude an Innovationen, span...",de,2026-01-08T19:14:09Z,adzuna,data_analyst,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
post_ai_full.isna().sum()

job_title           2285
job_description     2285
country             2285
date_posted         2285
source              2285
role                2285
id                   591
title                591
company              605
location             591
salary_min           591
salary_max           594
created              591
category             591
contract_type       2059
contract_time       1404
home_url             591
full_description     591
domain               591
clean_text           605
title_tokens         591
text_tokens          591
location_tokens      591
title_role           591
family_role          591
seniority            591
skills_list          591
industry             591
salary_avg           591
dtype: int64

In [91]:
post_ai_full = post_ai_full[[
    "job_title",
    "job_description",
    "country",
    "date_posted",
    "source",
    "role"
]]